fix to s3

diff --git a/.github/workflows/reusable-publish-layer.yml b/.github/workflows/reusable-publish-layer.yml
--- a/.github/workflows/reusable-publish-layer.yml
+++ b/.github/workflows/reusable-publish-layer.yml
@@ -3,10 +3,19 @@ name: "Reusable publish Lambda Layer"
 on:
   workflow_call:
     inputs:
-      AWS_LAMBDA_LAYERS_NAME:
+      artifact_name:
         type: string
         required: true
-      artifact_name:
+      s3_bucket_name:
+        type: string
+        required: true
+      s3_file_path:
+        type: string
+        required: true
+      lambda_layer_name:
+        type: string
+        required: true
+      lambda_layer_description:
         type: string
         required: true
     secrets:
@@ -15,8 +24,6 @@ on:
 
 env:
   AWS_ROLE_ARN: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ROLE_NAME }}"
-  download_artifact_path: "artifacts"
-  zip_file_name: "Layer.zip"
 
 permissions:
   id-token: write
@@ -35,17 +42,34 @@ jobs:
           aws-region: ap-northeast-1
           role-to-assume: ${{ env.AWS_ROLE_ARN }}
 
+      - name: "Get file basename"
+        id: file_basename
+        run: |
+          echo "BASENAME=$(basename ${{ inputs.s3_file_path }})" >> $GITHUB_OUTPUT
+
+      - name: "Validate file basename"
+        run: |
+          if [[ ! ${{ steps.file_basename.outputs.BASENAME }} =~ ^[^/]+$ ]]; then
+            echo "Error: Invalid file basename"
+            exit 1
+          fi
+
       - name: "Download artifact and to zip"
         uses: ./.github/actions/download-artifact-and-to-zip
         with:
           artifact_name: ${{ inputs.artifact_name }}
-          zip_file_name: ${{ env.zip_file_name }}
+          zip_file_name: ${{ steps.file_basename.outputs.BASENAME }}
 
-      - name: "Publish new layer version"
+      - name: "Upload to S3"
+        run: |
+          aws s3 cp "${{ steps.file_basename.outputs.BASENAME }}" "s3://${{ inputs.s3_file_path }}"
+
+      - name: "Publish layer version"
         id: publish_layer
         run: |
           aws lambda publish-layer-version \
-            --layer-name ${{ inputs.AWS_LAMBDA_LAYERS_NAME }} \
-            --zip-file fileb://${{ env.zip_file_name }} \
-            --compatible-runtimes nodejs \
-            --compatible-architectures x86_64
+          --layer-name ${{ inputs.lambda_layer_name }} \
+          --layer_ "${{ inputs.lambda_layer_description }}" \
+          --content "S3Bucket=${{ inputs.s3_bucket_name }},S3Key=${{ inputs.s3_file_path }}" \
+          --compatible-runtimes nodejs \
+          --compatible-architectures x86_64
